# Generated by Django 3.2.9 on 2023-06-24 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0014_auto_20191106_0844'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clothes',
            options={'ordering': ['create_time'], 'verbose_name': '产品信息', 'verbose_name_plural': '产品信息'},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['create_time'], 'verbose_name': '工序', 'verbose_name_plural': '工序'},
        ),
        migrations.RemoveField(
            model_name='clothes',
            name='color',
        ),
        migrations.RemoveField(
            model_name='clothes',
            name='size',
        ),
        migrations.AddField(
            model_name='clothes',
            name='danwei',
            field=models.SmallIntegerField(choices=[(1, '台'), (2, '套'), (3, '件'), (4, '个'), (5, '盒'), (6, '箱')], default=1, verbose_name='单位'),
        ),
        migrations.AddField(
            model_name='clothes',
            name='lei',
            field=models.SmallIntegerField(choices=[(1, '一类'), (2, '二类'), (3, '三类')], default=1, verbose_name='类别'),
        ),
        migrations.AddField(
            model_name='clothes',
            name='stock_down',
            field=models.PositiveIntegerField(default='1', verbose_name='最低库存'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='jx',
            field=models.CharField(default=1, max_length=32, verbose_name='机型'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clothes',
            name='name',
            field=models.CharField(max_length=32, verbose_name='机件名'),
        ),
        migrations.AlterField(
            model_name='clothes',
            name='sn',
            field=models.CharField(max_length=32, unique=True, verbose_name='机件号'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.CharField(max_length=32, verbose_name='车号'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=32, verbose_name='工序'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=32, verbose_name='车间'),
        ),
        migrations.AlterField(
            model_name='inorder',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.customer', verbose_name='工序'),
        ),
        migrations.AlterField(
            model_name='inorderclothes',
            name='clothes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.clothes', verbose_name='产品信息'),
        ),
        migrations.AlterField(
            model_name='outorder',
            name='clothes',
            field=models.ManyToManyField(through='common.OutorderClothes', to='common.Clothes', verbose_name='产品信息'),
        ),
        migrations.AlterField(
            model_name='outorder',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.customer', verbose_name='工序'),
        ),
        migrations.AlterField(
            model_name='outorder',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.user', verbose_name='出库员'),
        ),
        migrations.AlterField(
            model_name='outorderclothes',
            name='clothes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.clothes', verbose_name='产品信息'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('出库员', '出库员'), ('管理员', '管理员')], default='出库员', max_length=32, verbose_name='角色'),
        ),
    ]
