# Generated by Django 3.2.9 on 2023-06-26 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0016_auto_20230625_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inorder',
            name='clothes',
            field=models.ManyToManyField(through='common.InorderClothes', to='common.Clothes', verbose_name='器材'),
        ),
    ]
