# Generated by Django 3.2.9 on 2023-06-27 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0017_alter_inorder_clothes'),
    ]

    operations = [
        migrations.AddField(
            model_name='inorder',
            name='bumen',
            field=models.SmallIntegerField(choices=[('前纺', '前纺'), ('细纱', '细纱'), ('后纺', '后纺')], default=1, verbose_name='部门'),
        ),
    ]
