# Generated by Django 3.2.9 on 2023-06-27 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0018_inorder_bumen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inorder',
            name='bumen',
            field=models.SmallIntegerField(choices=[(1, '前纺'), (2, '细纱'), (3, '后纺')], default=1, verbose_name='部门'),
        ),
    ]
