# Generated by Django 3.2.19 on 2023-06-27 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0019_alter_inorder_bumen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inorder',
            name='bumen',
        ),
    ]
