# Generated by Django 3.2.9 on 2023-07-10 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0020_remove_inorder_bumen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('division', models.CharField(choices=[('前纺', '前纺'), ('细纱', '细纱'), ('后纺', '后纺')], default='前纺', max_length=32, verbose_name='部门')),
            ],
            options={
                'verbose_name': '部门',
                'verbose_name_plural': '部门',
            },
        ),
    ]
