# Generated by Django 3.2.9 on 2023-07-10 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0021_division'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='division',
            name='division',
        ),
        migrations.AddField(
            model_name='division',
            name='danwei',
            field=models.SmallIntegerField(choices=[(1, '前纺'), (2, '细纱'), (3, '后纺')], default=1, verbose_name='部门'),
        ),
    ]
