# Generated by Django 3.2.9 on 2023-07-10 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0022_auto_20230710_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='inorder',
            name='danwei',
            field=models.SmallIntegerField(choices=[(1, '前纺'), (2, '细纱'), (3, '后纺')], default=1, verbose_name='部门'),
        ),
    ]
