# Generated by Django 3.2.9 on 2023-07-10 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0023_inorder_danwei'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inorder',
            old_name='danwei',
            new_name='department',
        ),
    ]
