# Generated by Django 3.2.19 on 2023-07-10 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0024_rename_danwei_inorder_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='标题')),
            ],
        ),
        migrations.DeleteModel(
            name='Division',
        ),
        migrations.RemoveField(
            model_name='inorder',
            name='department',
        ),
    ]
