# Generated by Django 3.2.19 on 2023-07-10 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0026_auto_20230710_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothes',
            name='stock',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='库存'),
        ),
    ]
