# Generated by Django 3.2.9 on 2023-07-21 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0027_alter_clothes_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothes',
            name='stock',
            field=models.DecimalField(decimal_places=2, max_digits=7, verbose_name='库存'),
        ),
    ]
