# Generated by Django 3.2.9 on 2023-07-27 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0028_alter_clothes_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='Man',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='领取人')),
            ],
            options={
                'verbose_name': '领取人',
                'verbose_name_plural': '领取人',
                'ordering': ['id'],
            },
        ),
        migrations.AlterField(
            model_name='clothes',
            name='stock_down',
            field=models.DecimalField(decimal_places=2, max_digits=7, verbose_name='最低库存'),
        ),
    ]
