# Generated by Django 3.2.9 on 2023-07-27 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0030_outorder_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='man',
            name='name',
            field=models.CharField(max_length=32, null=True, verbose_name='领取人'),
        ),
    ]
