# Generated by Django 3.2.9 on 2023-07-28 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0031_alter_man_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='man',
            name='name',
            field=models.CharField(default=1, max_length=32, verbose_name='领取人'),
            preserve_default=False,
        ),
    ]
