# Generated by Django 3.2.9 on 2023-08-04 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0032_alter_man_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outorder',
            name='name',
        ),
        migrations.AddField(
            model_name='outorderclothes',
            name='name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='common.man', verbose_name='领取人'),
            preserve_default=False,
        ),
    ]
