# Generated by Django 3.2.9 on 2023-08-23 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0034_outorderclothes_create_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothes',
            name='danwei',
            field=models.SmallIntegerField(choices=[(1, '台'), (2, '套'), (3, '件'), (4, '个'), (5, '盒'), (6, '箱'), (7, '斤')], default=1, verbose_name='单位'),
        ),
    ]
