# Generated by Django 3.2.22 on 2023-11-17 13:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0035_alter_clothes_danwei'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outorderclothes',
            name='create_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间'),
        ),
    ]
