# Generated by Django 3.2.22 on 2023-11-23 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0036_alter_outorderclothes_create_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='outorder',
            name='amount',
            field=models.DecimalField(decimal_places=3, default=None, max_digits=7, null=True, verbose_name='数量'),
        ),
        migrations.AddField(
            model_name='outorder',
            name='name',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='common.man', verbose_name='领取人'),
        ),
        migrations.AlterField(
            model_name='clothes',
            name='price',
            field=models.DecimalField(decimal_places=3, max_digits=10, verbose_name='价格'),
        ),
        migrations.AlterField(
            model_name='outorderclothes',
            name='amount',
            field=models.DecimalField(decimal_places=3, max_digits=7, verbose_name='数量'),
        ),
        migrations.CreateModel(
            name='Outbound',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, verbose_name='出库单号')),
                ('amount', models.DecimalField(decimal_places=3, max_digits=7, verbose_name='数量')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('modify_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('clothes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.clothes', verbose_name='产品信息')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.customer', verbose_name='车号')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.man', verbose_name='领取人')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.user', verbose_name='出库员')),
            ],
            options={
                'verbose_name': '出库单',
                'verbose_name_plural': '出库单',
                'ordering': ['create_time'],
            },
        ),
        migrations.CreateModel(
            name='Inbound',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, verbose_name='入库单号')),
                ('price', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='二次价格')),
                ('amount', models.DecimalField(decimal_places=3, max_digits=7, verbose_name='数量')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('modify_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('clothes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.clothes', verbose_name='产品信息')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.department', verbose_name='部门')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.user', verbose_name='用户')),
            ],
            options={
                'verbose_name': '入库单',
                'verbose_name_plural': '入库单',
                'ordering': ['create_time'],
            },
        ),
    ]
