# Generated by Django 3.2.22 on 2023-12-07 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0037_auto_20231123_1415'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inbound',
            options={'ordering': ['id'], 'verbose_name': '入库单', 'verbose_name_plural': '入库单'},
        ),
        migrations.AlterModelOptions(
            name='inorder',
            options={'ordering': ['id'], 'verbose_name': '入库单', 'verbose_name_plural': '入库单'},
        ),
        migrations.AlterModelOptions(
            name='outbound',
            options={'ordering': ['id'], 'verbose_name': '出库单', 'verbose_name_plural': '出库单'},
        ),
        migrations.AlterModelOptions(
            name='outorder',
            options={'ordering': ['id'], 'verbose_name': '出库单', 'verbose_name_plural': '出库单'},
        ),
    ]
