# Generated by Django 3.2.22 on 2023-12-07 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0038_auto_20231207_1505'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inbound',
            name='customer',
        ),
    ]
